# Generated by Django 2.1.7 on 2019-07-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20190710_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Active',
            field=models.BooleanField(default=False),
        ),
    ]
