# Generated by Django 2.1.7 on 2019-07-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_client_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Verified',
            field=models.BooleanField(default=False),
        ),
    ]
