# Generated by Django 2.1.7 on 2019-07-17 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_client_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='Active',
        ),
    ]
